### ISSUE TITLE
[BUG] Pls help i have a problem with google colab server i was trying to run a minecraft server with google colab and i run it 4 or 5 times and now i cant iniciate and when we was playing if one go off then he cant come back, "disconnected" now i cant iniciate

### ISSUE THREAD

**Issue by Pa3loNF** [thecoder-001/MineColab#107]
i was trying to run a minecraft server with google colab and i run it 4 or 5 times and now i cant iniciate and when  we was playing if one go off then  he cant come back, "disconnected" now i cant iniciate

Procedding to use ngrok
Get your authtoken from https://dashboard.ngrok.com/auth
Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
Your server address is 0.tcp.eu.ngrok.io:15959
Starting server...
[21:07:34] [main/INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 39.1.0, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, nogui]
[21:07:34] [main/INFO]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.10 by Private Build
[21:07:35] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/content/drive/MyDrive/Minecraft-server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319!/ Service=ModLauncher Env=SERVER
[21:07:35] [main/INFO]: Found mod file [1.18.1] SecurityCraft v1.9.0.2-beta1 (1).jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file bonsaitrees3-3.0.4.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file cgm-1.2.1-1.18.1 (1).jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file CreativeCore_v2.5.0_mc1.18.1.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file easy_villagers-1.18.1-1.0.2.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file elevatorid-1.18-1.8.3.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file framework-0.2.3-1.18.1.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file Jade-1.18.1-4.4.1.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file jei-1.18.1-9.4.1.172.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file libnonymous-2.0.5.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file Mantle-1.18.1-1.8.37.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file PlayerRevive_v2.0.0-pre08_mc1.18.1.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file sophisticatedbackpacks-1.18.1-3.15.15.550.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file TConstruct-1.18.1-3.4.2.60.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file tl_skin_cape_forge_1.18_1.18.2-1.25.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file tombstone-7.4.1-1.18.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:35] [main/INFO]: Found mod file Xaeros_Minimap_22.3.0_Forge_1.18.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[21:07:36] [main/INFO]: Found mod file fmlcore-1.18.1-39.1.0.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@21baa903
[21:07:36] [main/INFO]: Found mod file javafmllanguage-1.18.1-39.1.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@21baa903
[21:07:36] [main/INFO]: Found mod file mclanguage-1.18.1-39.1.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@21baa903
[21:07:36] [main/INFO]: Found mod file server-1.18.1-20211210.034407-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@21baa903
[21:07:36] [main/INFO]: Found mod file forge-1.18.1-39.1.0-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@21baa903
[21:07:43] [main/INFO]: Compatibility level set to JAVA_17
[21:07:44] [main/INFO]: Successfully loaded Mixin Connector [org.tlauncher.MixinConnector]
[21:07:44] [main/INFO]: Launching target 'forgeserver' with arguments [nogui]
[21:07:44] [main/WARN]: Error loading class: de/maxhenkel/gravestone/events/DeathEvents (java.lang.ClassNotFoundException: de.maxhenkel.gravestone.events.DeathEvents)
[21:07:44] [main/WARN]: Error loading class: de/maxhenkel/corpse/events/DeathEvents (java.lang.ClassNotFoundException: de.maxhenkel.corpse.events.DeathEvents)
[21:07:44] [main/FATAL]: Attempted to load class net/minecraft/client/player/AbstractClientPlayer for invalid dist DEDICATED_SERVER
[21:07:44] [main/WARN]: Error loading class: net/minecraft/client/player/AbstractClientPlayer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/AbstractClientPlayer for invalid dist DEDICATED_SERVER)
[21:07:44] [main/WARN]: @Mixin target net.minecraft.client.player.AbstractClientPlayer was not found tlskincape-mixins.json:MixinAbstractPlayer
[21:07:44] [main/FATAL]: Attempted to load class net/minecraft/client/gui/screens/TitleScreen for invalid dist DEDICATED_SERVER
[21:07:44] [main/WARN]: Error loading class: net/minecraft/client/gui/screens/TitleScreen (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/TitleScreen for invalid dist DEDICATED_SERVER)
[21:07:44] [main/WARN]: @Mixin target net.minecraft.client.gui.screens.TitleScreen was not found tlskincape-mixins.json:MixinMainMenu
[21:07:45] [main/WARN]: Error loading class: net/minecraft/client/model/PlayerModel (java.lang.ClassNotFoundException: net.minecraft.client.model.PlayerModel)
[21:07:45] [main/WARN]: @Mixin target net.minecraft.client.model.PlayerModel was not found tlskincape-mixins.json:MixinPlayerModel
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
[21:08:07] [modloading-worker-0/INFO]: Forge mod loading, version 39.1.0, for MC 1.18.1 with MCP 20211210.034407
[21:08:07] [modloading-worker-0/INFO]: MinecraftForge v39.1.0 Initialized
[21:08:19] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `milk`, expected `forge`. This could be a intended override, but in most cases indicates a broken mod.
[21:08:19] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `flowing_milk`, expected `forge`. This could be a intended override, but in most cases indicates a broken mod.
[21:08:22] [main/INFO]: Registered synced data key cgm:aiming for minecraft:player
[21:08:22] [main/INFO]: Registered synced data key cgm:shooting for minecraft:player
[21:08:22] [main/INFO]: Registered synced data key cgm:reloading for minecraft:player
[21:08:22] [modloading-worker-0/INFO]: Loading Xaero's Minimap - Stage 1/2 (Server)
[21:08:22] [main/INFO]: Loading Xaero's Minimap - Stage 2/2 (Server)
[21:08:22] [modloading-worker-0/INFO]: Start loading plugin at mcp.mobius.waila.addons.core.CorePlugin
[21:08:22] [modloading-worker-0/INFO]: Start loading plugin at ovh.corail.tombstone.compatibility.IntegrationWaila
[21:08:22] [modloading-worker-0/INFO]: Start loading plugin at snownee.jade.VanillaPlugin
[21:08:22] [Forge Version Check/INFO]: [tombstone] Starting version check at https://raw.githubusercontent.com/Corail31/tombstone_lite/master/update.json
[21:08:22] [modloading-worker-0/INFO]: Start loading plugin at de.maxhenkel.easyvillagers.integration.waila.PluginEasyVillagers
[21:08:22] [modloading-worker-0/INFO]: Start loading plugin at net.geforcemods.securitycraft.compat.waila.WailaDataProvider
[21:08:22] [modloading-worker-0/ERROR]: Error loading plugin at net.geforcemods.securitycraft.compat.waila.WailaDataProvider
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/Rect2i
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:2271) ~[?:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:263) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:231) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:186) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:180) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:174) ~[eventbus-5.0.3.jar%232!/:?]
	at net.geforcemods.securitycraft.compat.waila.WailaDataProvider.<clinit>(WailaDataProvider.java:68) ~[%5B1.18.1%5D%20SecurityCraft%20v1.9.0.2-beta1%20(1).jar%2337!/:1.9.0.2-beta1]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at mcp.mobius.waila.Waila.loadComplete(Waila.java:111) ~[Jade-1.18.1-4.4.1.jar%2344!/:4.4.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.1.0.jar%2357!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.1.0.jar%2356!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.Rect2i
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 30 more
[21:08:24] [Forge Version Check/INFO]: [tombstone] Found status: UP_TO_DATE Current: 7.4.1 Target: null
[21:08:24] [Forge Version Check/INFO]: [cgm] Starting version check at https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/cgm/update.json
[21:08:24] [Forge Version Check/INFO]: [cgm] Found status: BETA Current: 1.2.1 Target: null
[21:08:24] [Forge Version Check/INFO]: [framework] Starting version check at https://mrcrayfish.com/modupdatejson?id=framework
[21:08:25] [Forge Version Check/INFO]: [framework] Found status: BETA Current: 0.2.3 Target: 0.2.2
[21:08:25] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[21:08:25] [Forge Version Check/INFO]: [forge] Found status: UP_TO_DATE Current: 39.1.0 Target: null
[21:08:25] [Forge Version Check/INFO]: [easy_villagers] Starting version check at https://maxhenkel.de/update/easy_villagers.json
[21:08:27] [Forge Version Check/INFO]: [easy_villagers] Found status: UP_TO_DATE Current: 1.18.1-1.0.2 Target: null
[21:08:27] [Forge Version Check/INFO]: [securitycraft] Starting version check at https://www.github.com/Geforce132/SecurityCraft/raw/master/Updates/Forge.json
[21:08:27] [Forge Version Check/INFO]: [securitycraft] Found status: UP_TO_DATE Current: 1.9.0.2-beta1 Target: null
[21:08:33] [main/INFO]: Environment: authHost='https://authserver.mojang.com/', accountsHost='https://api.mojang.com/', sessionHost='https://sessionserver.mojang.com/', servicesHost='https://api.minecraftservices.com/', name='PROD'
[21:08:33] [main/INFO]: Injecting existing registry data into this CLIENT instance
[21:08:41] [main/WARN]: Assets URL 'union:/content/drive/MyDrive/Minecraft-server/libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-srg.jar%2355!/assets/.mcassetsroot' uses unexpected schema
[21:08:41] [main/WARN]: Assets URL 'union:/content/drive/MyDrive/Minecraft-server/libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-srg.jar%2355!/data/.mcassetsroot' uses unexpected schema
[21:08:42] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:08:42] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:08:42] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:08:42] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[21:08:42] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[21:08:43] [main/INFO]: Reloading ResourceManager: Default, bukkit, forge-1.18.1-39.1.0-universal.jar, [1.18.1] SecurityCraft v1.9.0.2-beta1 (1).jar, TConstruct-1.18.1-3.4.2.60.jar, libnonymous-2.0.5.jar, elevatorid-1.18-1.8.3.jar, tombstone-7.4.1-1.18.jar, sophisticatedbackpacks-1.18.1-3.15.15.550.jar, bonsaitrees3-3.0.4.jar, cgm-1.2.1-1.18.1 (1).jar, Jade-1.18.1-4.4.1.jar, CreativeCore_v2.5.0_mc1.18.1.jar, jei-1.18.1-9.4.1.172.jar, framework-0.2.3-1.18.1.jar, easy_villagers-1.18.1-1.0.2.jar, tl_skin_cape_forge_1.18_1.18.2-1.25.jar, Mantle-1.18.1-1.8.37.jar, Xaeros_Minimap_22.3.0_Forge_1.18.jar, PlayerRevive_v2.0.0-pre08_mc1.18.1.jar
[21:09:42] [Worker-Main-2/INFO]: Loaded 23 recipes
[21:09:58] [Worker-Main-2/INFO]: Loaded 2308 advancements
[21:09:58] [Worker-Main-2/ERROR]: Invalid material redirect tconstruct:tinkers_bronze as material tconstruct:bronze does not exist
[21:09:58] [Worker-Main-2/INFO]: Loaded 48 materials in 39.866787 ms
[21:09:59] [Worker-Main-2/INFO]: 128 stats loaded for 67 materials in 382.07642 ms
[21:09:59] [Worker-Main-2/INFO]: 56 traits loaded for 67 materials in 224.57603 ms
[21:09:59] [Worker-Main-2/INFO]: Loaded 26 tool definitions in 103.258804 ms
[21:09:59] [Worker-Main-2/INFO]: Loaded 16 station slot layouts in 132.09715 ms
[21:10:07] [Server thread/INFO]: Starting minecraft server version 1.18.1
[21:10:07] [Server thread/INFO]: Loading properties
[21:10:07] [Server thread/INFO]: Default game type: SURVIVAL
[21:10:07] [Server thread/INFO]: Generating keypair
[21:10:07] [Server thread/INFO]: Starting Minecraft server on *:25565
[21:10:07] [Server thread/INFO]: Using epoll channel type
[21:10:07] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[21:10:07] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[21:10:07] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[21:10:07] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[21:10:08] [Server thread/INFO]: Preparing level "world"
[21:10:08] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[21:10:12] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:12] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:12] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:12] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:12] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:12] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:12] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:12] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:12] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:13] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:13] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:14] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:14] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:16] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:16] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:16] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:16] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:17] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:17] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:18] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:20] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:20] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:21] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[21:10:21] [Worker-Main-2/INFO]: Preparing spawn area: 3%
[21:10:22] [Worker-Main-2/INFO]: Preparing spawn area: 3%
[21:10:22] [Worker-Main-2/INFO]: Preparing spawn area: 10%
[21:10:23] [Worker-Main-2/INFO]: Preparing spawn area: 10%
[21:10:23] [Worker-Main-2/INFO]: Preparing spawn area: 10%
[21:10:25] [Worker-Main-2/INFO]: Preparing spawn area: 18%
[21:10:25] [Worker-Main-2/INFO]: Preparing spawn area: 18%
[21:10:25] [Worker-Main-2/INFO]: Preparing spawn area: 19%
[21:10:25] [Worker-Main-2/INFO]: Preparing spawn area: 24%
[21:10:26] [Worker-Main-2/INFO]: Preparing spawn area: 31%
[21:10:26] [Worker-Main-2/INFO]: Preparing spawn area: 38%
[21:10:27] [Worker-Main-2/INFO]: Preparing spawn area: 40%
[21:10:27] [Worker-Main-2/INFO]: Preparing spawn area: 45%
[21:10:28] [Worker-Main-2/INFO]: Preparing spawn area: 45%
[21:10:28] [Worker-Main-2/INFO]: Preparing spawn area: 50%
[21:10:29] [Worker-Main-2/INFO]: Preparing spawn area: 53%
[21:10:29] [Worker-Main-2/INFO]: Preparing spawn area: 58%
[21:10:30] [Worker-Main-2/INFO]: Preparing spawn area: 71%
[21:10:30] [Worker-Main-2/INFO]: Preparing spawn area: 72%
[21:10:31] [Worker-Main-2/INFO]: Preparing spawn area: 72%
[21:10:31] [Worker-Main-2/INFO]: Preparing spawn area: 72%
[21:10:33] [Server thread/INFO]: Time elapsed: 24433 ms
[21:10:33] [Server thread/INFO]: Done (25.169s)! For help, type "help"
[21:10:33] [Server thread/INFO]: Successfully initialized permission handler forge:default_handler

**Comment by N-aksif-N** [comment]
Hello, If you don't might, try this: https://github.com/N-aksif-N/MineColab_Improved
It's a improvement for minecolab

**Comment by ghost** [comment]
> Hello, If you don't might, try this: https://github.com/N-aksif-N/MineColab_Improved It's a improvement for minecolab

lemme see
