### ISSUE TITLE
[BUG] i need help with my minecolab sv pls help

### ISSUE THREAD

**Issue by Pa3loNF** [thecoder-001/MineColab#108]
**Expected behavior**
today i could run the server but now if i try to enter put "disconnected"

**Minecraft server Version**
1.18.1

Starting server...
[13:10:45] [main/INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 39.1.0, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, nogui]
[13:10:45] [main/INFO]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.10 by Private Build
[13:10:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/content/drive/MyDrive/Minecraft-server/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319!/ Service=ModLauncher Env=SERVER
[13:10:46] [main/INFO]: Found mod file [1.18.1] SecurityCraft v1.9.0.2-beta1 (1).jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file bonsaitrees3-3.0.4.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file cgm-1.2.1-1.18.1 (1).jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file CreativeCore_v2.5.0_mc1.18.1.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file easy_villagers-1.18.1-1.0.2.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file elevatorid-1.18-1.8.3.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file framework-0.2.3-1.18.1.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file Jade-1.18.1-4.4.1.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file jei-1.18.1-9.4.1.172.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file libnonymous-2.0.5.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file Mantle-1.18.1-1.8.37.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file PlayerRevive_v2.0.0-pre08_mc1.18.1.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file sophisticatedbackpacks-1.18.1-3.15.15.550.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file TConstruct-1.18.1-3.4.2.60.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file tl_skin_cape_forge_1.18_1.18.2-1.25.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file tombstone-7.4.1-1.18.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:46] [main/INFO]: Found mod file Xaeros_Minimap_22.3.0_Forge_1.18.jar of type MOD with locator {mods folder locator at /content/drive/MyDrive/Minecraft-server/mods}
[13:10:47] [main/INFO]: Found mod file fmlcore-1.18.1-39.1.0.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@21baa903
[13:10:47] [main/INFO]: Found mod file javafmllanguage-1.18.1-39.1.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@21baa903
[13:10:47] [main/INFO]: Found mod file mclanguage-1.18.1-39.1.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@21baa903
[13:10:47] [main/INFO]: Found mod file server-1.18.1-20211210.034407-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@21baa903
[13:10:47] [main/INFO]: Found mod file forge-1.18.1-39.1.0-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@21baa903
[13:10:55] [main/INFO]: Compatibility level set to JAVA_17
[13:10:55] [main/INFO]: Successfully loaded Mixin Connector [org.tlauncher.MixinConnector]
[13:10:55] [main/INFO]: Launching target 'forgeserver' with arguments [nogui]
[13:10:57] [main/WARN]: Error loading class: de/maxhenkel/gravestone/events/DeathEvents (java.lang.ClassNotFoundException: de.maxhenkel.gravestone.events.DeathEvents)
[13:10:57] [main/WARN]: Error loading class: de/maxhenkel/corpse/events/DeathEvents (java.lang.ClassNotFoundException: de.maxhenkel.corpse.events.DeathEvents)
[13:10:57] [main/FATAL]: Attempted to load class net/minecraft/client/player/AbstractClientPlayer for invalid dist DEDICATED_SERVER
[13:10:57] [main/WARN]: Error loading class: net/minecraft/client/player/AbstractClientPlayer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/player/AbstractClientPlayer for invalid dist DEDICATED_SERVER)
[13:10:57] [main/WARN]: @Mixin target net.minecraft.client.player.AbstractClientPlayer was not found tlskincape-mixins.json:MixinAbstractPlayer
[13:10:57] [main/FATAL]: Attempted to load class net/minecraft/client/gui/screens/TitleScreen for invalid dist DEDICATED_SERVER
[13:10:57] [main/WARN]: Error loading class: net/minecraft/client/gui/screens/TitleScreen (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/TitleScreen for invalid dist DEDICATED_SERVER)
[13:10:57] [main/WARN]: @Mixin target net.minecraft.client.gui.screens.TitleScreen was not found tlskincape-mixins.json:MixinMainMenu
[13:10:57] [main/WARN]: Error loading class: net/minecraft/client/model/PlayerModel (java.lang.ClassNotFoundException: net.minecraft.client.model.PlayerModel)
[13:10:57] [main/WARN]: @Mixin target net.minecraft.client.model.PlayerModel was not found tlskincape-mixins.json:MixinPlayerModel
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
[13:11:22] [modloading-worker-0/INFO]: Forge mod loading, version 39.1.0, for MC 1.18.1 with MCP 20211210.034407
[13:11:22] [modloading-worker-0/INFO]: MinecraftForge v39.1.0 Initialized
[13:11:40] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `milk`, expected `forge`. This could be a intended override, but in most cases indicates a broken mod.
[13:11:40] [main/INFO]: Potentially Dangerous alternative prefix `minecraft` for name `flowing_milk`, expected `forge`. This could be a intended override, but in most cases indicates a broken mod.
[13:11:44] [main/INFO]: Registered synced data key cgm:aiming for minecraft:player
[13:11:44] [main/INFO]: Registered synced data key cgm:shooting for minecraft:player
[13:11:44] [main/INFO]: Registered synced data key cgm:reloading for minecraft:player
[13:11:44] [modloading-worker-0/INFO]: Loading Xaero's Minimap - Stage 1/2 (Server)
[13:11:44] [main/INFO]: Loading Xaero's Minimap - Stage 2/2 (Server)
[13:11:44] [Forge Version Check/INFO]: [tombstone] Starting version check at https://raw.githubusercontent.com/Corail31/tombstone_lite/master/update.json
[13:11:44] [modloading-worker-0/INFO]: Start loading plugin at mcp.mobius.waila.addons.core.CorePlugin
[13:11:44] [modloading-worker-0/INFO]: Start loading plugin at ovh.corail.tombstone.compatibility.IntegrationWaila
[13:11:44] [modloading-worker-0/INFO]: Start loading plugin at snownee.jade.VanillaPlugin
[13:11:44] [modloading-worker-0/INFO]: Start loading plugin at de.maxhenkel.easyvillagers.integration.waila.PluginEasyVillagers
[13:11:44] [modloading-worker-0/INFO]: Start loading plugin at net.geforcemods.securitycraft.compat.waila.WailaDataProvider
[13:11:44] [modloading-worker-0/ERROR]: Error loading plugin at net.geforcemods.securitycraft.compat.waila.WailaDataProvider
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/Rect2i
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:2271) ~[?:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:263) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:231) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:186) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:180) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.addListener(EventBus.java:174) ~[eventbus-5.0.3.jar%232!/:?]
	at net.geforcemods.securitycraft.compat.waila.WailaDataProvider.<clinit>(WailaDataProvider.java:68) ~[%5B1.18.1%5D%20SecurityCraft%20v1.9.0.2-beta1%20(1).jar%2337!/:1.9.0.2-beta1]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at mcp.mobius.waila.Waila.loadComplete(Waila.java:111) ~[Jade-1.18.1-4.4.1.jar%2344!/:4.4.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[javafmllanguage-1.18.1-39.1.0.jar%2357!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[fmlcore-1.18.1-39.1.0.jar%2356!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.Rect2i
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 30 more
[13:11:46] [Forge Version Check/INFO]: [tombstone] Found status: UP_TO_DATE Current: 7.4.1 Target: null
[13:11:46] [Forge Version Check/INFO]: [cgm] Starting version check at https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/cgm/update.json
[13:11:46] [Forge Version Check/INFO]: [cgm] Found status: BETA Current: 1.2.1 Target: null
[13:11:46] [Forge Version Check/INFO]: [framework] Starting version check at https://mrcrayfish.com/modupdatejson?id=framework
[13:11:46] [Forge Version Check/INFO]: [framework] Found status: BETA Current: 0.2.3 Target: 0.2.2
[13:11:46] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[13:11:47] [Forge Version Check/INFO]: [forge] Found status: UP_TO_DATE Current: 39.1.0 Target: null
[13:11:47] [Forge Version Check/INFO]: [easy_villagers] Starting version check at https://maxhenkel.de/update/easy_villagers.json
[13:11:48] [Forge Version Check/INFO]: [easy_villagers] Found status: UP_TO_DATE Current: 1.18.1-1.0.2 Target: null
[13:11:48] [Forge Version Check/INFO]: [securitycraft] Starting version check at https://www.github.com/Geforce132/SecurityCraft/raw/master/Updates/Forge.json
[13:11:48] [Forge Version Check/INFO]: [securitycraft] Found status: UP_TO_DATE Current: 1.9.0.2-beta1 Target: null
[13:11:58] [main/INFO]: Environment: authHost='https://authserver.mojang.com/', accountsHost='https://api.mojang.com/', sessionHost='https://sessionserver.mojang.com/', servicesHost='https://api.minecraftservices.com/', name='PROD'
[13:11:58] [main/INFO]: Injecting existing registry data into this CLIENT instance
[13:12:06] [main/WARN]: Assets URL 'union:/content/drive/MyDrive/Minecraft-server/libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-srg.jar%2355!/assets/.mcassetsroot' uses unexpected schema
[13:12:06] [main/WARN]: Assets URL 'union:/content/drive/MyDrive/Minecraft-server/libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-srg.jar%2355!/data/.mcassetsroot' uses unexpected schema
[13:12:08] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:12:08] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:12:08] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:12:08] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[13:12:08] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[13:12:08] [main/INFO]: Reloading ResourceManager: Default, bukkit, forge-1.18.1-39.1.0-universal.jar, [1.18.1] SecurityCraft v1.9.0.2-beta1 (1).jar, TConstruct-1.18.1-3.4.2.60.jar, libnonymous-2.0.5.jar, elevatorid-1.18-1.8.3.jar, tombstone-7.4.1-1.18.jar, sophisticatedbackpacks-1.18.1-3.15.15.550.jar, bonsaitrees3-3.0.4.jar, cgm-1.2.1-1.18.1 (1).jar, Jade-1.18.1-4.4.1.jar, CreativeCore_v2.5.0_mc1.18.1.jar, jei-1.18.1-9.4.1.172.jar, framework-0.2.3-1.18.1.jar, easy_villagers-1.18.1-1.0.2.jar, tl_skin_cape_forge_1.18_1.18.2-1.25.jar, Mantle-1.18.1-1.8.37.jar, Xaeros_Minimap_22.3.0_Forge_1.18.jar, PlayerRevive_v2.0.0-pre08_mc1.18.1.jar
[13:13:12] [Worker-Main-2/INFO]: Loaded 23 recipes
[13:13:33] [Worker-Main-2/INFO]: Loaded 2308 advancements
[13:13:33] [Worker-Main-2/ERROR]: Invalid material redirect tconstruct:tinkers_bronze as material tconstruct:bronze does not exist
[13:13:33] [Worker-Main-2/INFO]: Loaded 48 materials in 50.677586 ms
[13:13:33] [Worker-Main-2/INFO]: 128 stats loaded for 67 materials in 462.72748 ms
[13:13:34] [Worker-Main-2/INFO]: 56 traits loaded for 67 materials in 419.89218 ms
[13:13:34] [Worker-Main-2/INFO]: Loaded 26 tool definitions in 82.24645 ms
[13:13:34] [Worker-Main-2/INFO]: Loaded 16 station slot layouts in 222.05592 ms
[13:13:43] [Server thread/INFO]: Starting minecraft server version 1.18.1
[13:13:43] [Server thread/INFO]: Loading properties
[13:13:43] [Server thread/INFO]: Default game type: SURVIVAL
[13:13:43] [Server thread/INFO]: Generating keypair
[13:13:43] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:13:43] [Server thread/INFO]: Using epoll channel type
[13:13:43] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[13:13:43] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[13:13:43] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[13:13:43] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[13:13:44] [Server thread/INFO]: Preparing level "world"
[13:13:45] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:13:51] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:51] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:51] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:51] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:51] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:51] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:51] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:51] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:51] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:51] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:52] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:52] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:52] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:52] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:52] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:52] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:53] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:53] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:54] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:54] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:55] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:55] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:56] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:57] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:57] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:57] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:58] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:58] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:59] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:13:59] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:14:00] [Worker-Main-2/INFO]: Preparing spawn area: 3%
[13:14:00] [Worker-Main-2/INFO]: Preparing spawn area: 4%
[13:14:01] [Worker-Main-2/INFO]: Preparing spawn area: 4%
[13:14:01] [Worker-Main-2/INFO]: Preparing spawn area: 6%
[13:14:02] [Worker-Main-2/INFO]: Preparing spawn area: 7%
[13:14:02] [Worker-Main-2/INFO]: Preparing spawn area: 9%
[13:14:03] [Worker-Main-2/INFO]: Preparing spawn area: 10%
[13:14:03] [Worker-Main-2/INFO]: Preparing spawn area: 12%
[13:14:06] [Worker-Main-2/INFO]: Preparing spawn area: 13%
[13:14:06] [Worker-Main-2/INFO]: Preparing spawn area: 13%
[13:14:06] [Worker-Main-2/INFO]: Preparing spawn area: 13%
[13:14:06] [Worker-Main-2/INFO]: Preparing spawn area: 13%
[13:14:06] [Worker-Main-2/INFO]: Preparing spawn area: 13%
[13:14:06] [Worker-Main-2/INFO]: Preparing spawn area: 15%
[13:14:07] [Worker-Main-2/INFO]: Preparing spawn area: 17%
[13:14:07] [Worker-Main-2/INFO]: Preparing spawn area: 20%
[13:14:08] [Worker-Main-2/INFO]: Preparing spawn area: 21%
[13:14:09] [Worker-Main-2/INFO]: Preparing spawn area: 21%
[13:14:09] [Worker-Main-2/INFO]: Preparing spawn area: 21%
[13:14:09] [Worker-Main-2/INFO]: Preparing spawn area: 32%
[13:14:10] [Worker-Main-2/INFO]: Preparing spawn area: 45%
[13:14:10] [Worker-Main-2/INFO]: Preparing spawn area: 45%
[13:14:12] [Worker-Main-2/INFO]: Preparing spawn area: 45%
[13:14:12] [Worker-Main-2/INFO]: Preparing spawn area: 45%
[13:14:12] [Worker-Main-2/INFO]: Preparing spawn area: 45%
[13:14:12] [Worker-Main-2/INFO]: Preparing spawn area: 45%
[13:14:13] [Worker-Main-2/INFO]: Preparing spawn area: 53%
[13:14:13] [Worker-Main-2/INFO]: Preparing spawn area: 57%
[13:14:14] [Worker-Main-2/INFO]: Preparing spawn area: 61%
[13:14:14] [Worker-Main-2/INFO]: Preparing spawn area: 64%
[13:14:15] [Worker-Main-2/INFO]: Preparing spawn area: 64%
[13:14:15] [Worker-Main-2/INFO]: Preparing spawn area: 71%
[13:14:16] [Worker-Main-2/INFO]: Preparing spawn area: 74%
[13:14:16] [Worker-Main-2/INFO]: Preparing spawn area: 80%
[13:14:17] [Worker-Main-2/INFO]: Preparing spawn area: 82%
[13:14:17] [Worker-Main-2/INFO]: Preparing spawn area: 84%
[13:14:18] [Worker-Main-2/INFO]: Preparing spawn area: 86%
[13:14:18] [Worker-Main-2/INFO]: Preparing spawn area: 86%
[13:14:19] [Worker-Main-2/INFO]: Preparing spawn area: 88%
[13:14:22] [Worker-Main-2/INFO]: Preparing spawn area: 89%
[13:14:22] [Worker-Main-2/INFO]: Preparing spawn area: 89%
[13:14:22] [Worker-Main-2/INFO]: Preparing spawn area: 89%
[13:14:22] [Worker-Main-2/INFO]: Preparing spawn area: 89%
[13:14:22] [Worker-Main-2/INFO]: Preparing spawn area: 89%
[13:14:22] [Worker-Main-2/INFO]: Preparing spawn area: 89%
[13:14:22] [Worker-Main-2/INFO]: Preparing spawn area: 89%
[13:14:23] [Worker-Main-2/INFO]: Preparing spawn area: 92%
[13:14:23] [Worker-Main-2/INFO]: Preparing spawn area: 94%
[13:14:24] [Worker-Main-2/INFO]: Preparing spawn area: 97%
[13:14:24] [Server thread/INFO]: Time elapsed: 39482 ms
[13:14:24] [Server thread/INFO]: Done (40.706s)! For help, type "help"
[13:14:24] [Server thread/INFO]: Successfully initialized permission handler forge:default_handler

**Comment by N-aksif-N** [comment]
Hello, If you don't might, try this: https://github.com/N-aksif-N/MineColab_Improved
It's a improvement for minecolab
