### ISSUE TITLE
NO X11 DISPLAY

### ISSUE THREAD

**Issue by ivanlm2604** [thecoder-001/MineColab#116]
it says no x11 DISPLAY variable and I don't know what to do, please help

java.awt.HeadlessException: 

No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.init(Window.java:501)
	at java.desktop/java.awt.Window.<init>(Window.java:453)
	at java.desktop/java.awt.Window.<init>(Window.java:608)
	at java.desktop/java.awt.Dialog.<init>(Dialog.java:675)
	at java.desktop/java.awt.Dialog.<init>(Dialog.java:520)
	at java.desktop/javax.swing.JDialog.<init>(JDialog.java:423)
	at java.desktop/javax.swing.JOptionPane.createDialog(JOptionPane.java:956)
	at net.minecraftforge.installer.InstallerPanel.run(InstallerPanel.java:279)
	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:182)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:154)
Exception in thread "main" 
java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/java.awt.Frame.<init>(Frame.java:393)
	at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
	at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
	at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1695)
	at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:874)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:676)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:647)
	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:185)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:154)

**Comment by N-aksif-N** [comment]
add this !export DISPLAY=:0.0 to your code

**Comment by N-aksif-N** [comment]
Hi @ivanlm2604, this is an advertisement about another project: [Minecolab_Improved](https://github.com/N-aksif-N/MineColab_Improved).

It may be helped you about your issues. Have a nice day!

**Comment by N-aksif-N** [comment]
May be this helped too, https://github.com/thecoder-001/MineColab/issues/88

**Comment by ivanlm2604** [comment]
thanks !!!
