### ISSUE TITLE
[BUG] Minecolab doesn't work for 1.18 server

### ISSUE THREAD

**Issue by nellowly** [thecoder-001/MineColab#43]
**Describe the bug**
```
[15:21:34] [Server thread/INFO]: Preparing level "world"
[15:21:34] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: jdk.jfr.FlightRecorderListener
	at net.minecraft.server.MinecraftServer.e_(SourceFile:354) ~[server.jar:?]
	at aav.e(SourceFile:184) ~[server.jar:?]
	at net.minecraft.server.MinecraftServer.x(SourceFile:695) [server.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:280) [server.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$3871/0x000000001ca19a38.run(Unknown Source) [server.jar:?]
	at java.lang.Thread.run(Thread.java:853) [?:?]
Caused by: java.lang.ClassNotFoundException: jdk.jfr.FlightRecorderListener
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:822) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:1106) ~[?:?]
	... 6 more
[15:21:34] [Server thread/ERROR]: This crash report has been saved to: /content/drive/MyDrive/Minecraft-server/./crash-reports/crash-2021-08-14_15.21.34-server.txt
[15:21:34] [Server thread/INFO]: Stopping server
[15:21:34] [Server thread/INFO]: Saving players
[15:21:34] [Server thread/INFO]: Saving worlds
[15:21:34] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "abu.o_()" because "â˜ƒ" is null
	at net.minecraft.server.MinecraftServer.a(SourceFile:622) ~[server.jar:?]
	at net.minecraft.server.MinecraftServer.u(SourceFile:649) ~[server.jar:?]
	at aav.u(SourceFile:585) ~[server.jar:?]
	at net.minecraft.server.MinecraftServer.x(SourceFile:761) [server.jar:?]
	at net.minecraft.server.MinecraftServer.a(SourceFile:280) [server.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$3871/0x000000001ca19a38.run(Unknown Source) [server.jar:?]
	at java.lang.Thread.run(Thread.java:853) [?:?]
````

**To Reproduce**
`url = 'https://launcher.mojang.com/v1/objects/cbe106c19f5072222ce54039aa665a8aaf97097d/server.jar'` in second code block

**Minecraft server Version**
Minecraft 1.18 Exprimental Snapshot 3

It is working fine on my computer (I can connect to it)

![](https://cdn.discordapp.com/attachments/686387177902702626/876134090187898900/unknown.png)

I know it is still in snapshot but I believe there shouldn't be a different behavior with java on google colab.

**Comment by AndreVuillemot160** [comment]
Why you downloaded an Minecraft 1.18 in first place?

**Comment by AndreVuillemot160** [comment]
Maybe the issue in openj9, the reason why we even use it, is because it's supporting ubuntu 18.04

**Comment by nellowly** [comment]
I just want the caves and cliffs update :<

**Comment by AndreVuillemot160** [comment]
I am curious if 1.18 works now lmao

**Comment by tuwuna** [comment]
The server works for me on the latest snapshot. I think it was mojang's fault

You can close this issue now :)

**Comment by nellowly** [comment]
The server works for me on the latest [server.jar](https://launcher.mojang.com/v1/objects/2b40ef4bf57b2040f7d9affb48c0131b228f954f/server.jar) so it was Mojang's fault

Closing this issue... Thanks you :)

**Comment by AndreVuillemot160** [comment]
Hooray! Now our man @nellowly can play Minecraft haha
