### ISSUE TITLE
[BUG] Error while logging in

### ISSUE THREAD

**Issue by Polikopp** [thecoder-001/MineColab#5]
**Describe the bug**
As soon as I enter the ngrok ip address in my server list, an error in the console appears which causes the server to crash completely. (I don't even see it turning on in my server list)

All the steps go smoothly until the moment I try to log in.
In the configuration file, I put version 1.8.8

Here is the error:
`[12:10:02] [Netty Epoll Server IO #1/WARN]: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.RuntimeException: Unable to access address of buffer
	at io.netty.channel.epoll.Native.read(Native Method) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.doReadBytes(EpollSocketChannel.java:678) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:714) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe$3.run(EpollSocketChannel.java:755) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268) [patched.jar:git-PaperSpigot-"4c7641d"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
`

There is also a warning at the start of launch when it indicates the port:
`[12:09:19] [Server thread/INFO]: Starting Minecraft server on *:25565
[12:09:19] [Server thread/INFO]: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.`

Here are the full logs (the error is repeated endlessly, I truncated the end of the file): [latest.log](https://github.com/thecoder-001/MineColab/files/5401640/latest.log)

**Comment by thecoder-001** [comment]
Hello Polikopp! Thanks for opening an issue.
I have never stumbled across this error during my testing. Looks like its depends on the hardware available at that time.
Cay you try to edit your `server.properties` and change `use-native-transport` to `false`. It might result in slightly lower performance, but not noticeable. 
ps: If you are wondering what it does, its just some linux server performance improvements by optimizing packet sending/receiving. Several people seem to have problem with it on certain restricted hardwares, so this might work.

**Comment by Polikopp** [comment]
Hello, thank you for your answer. I changed the value but it didn't change anything. After some research and some tests, by putting java 8, it worked. So I'm going to leave java 8 for now.
