### ISSUE TITLE
[BUG] cant initialize server

### ISSUE THREAD

**Issue by Ismasan99** [thecoder-001/MineColab#84]
**Describe the bug**
An error displays saying no x11 display variable was set

**To Reproduce**
1. just execute
2. error plays

**Expected behavior**
the server to run

**Screenshots**
Exception in thread "main" 
java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/java.awt.Frame.<init>(Frame.java:393)
	at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
	at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
	at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1695)
	at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:874)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:676)
	at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:647)
	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:191)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:161)

**Minecraft server Version**
1.19.2 forge

**Mod/Datapack list**
List all the mods/datapacks currently being used on the server if applicable.

**Additional context**

**Comment by Fadri5** [comment]
Hi, im having the same problem, have you found a solution yet?
