### ISSUE TITLE
[BUG] Server not being able to launch due to opendjk version being incorrect

### ISSUE THREAD

**Issue by notyoutuber1** [thecoder-001/MineColab#93]
**Describe the bug**
This bug occurs when the version is less than 1.17 and it is also forge, which doesn't allow it to run the server

**To Reproduce**
1.Set the version 1.12.2 (less than 1.17)
2. Set the loader to forge
3. Scroll to the 2nd cell's output

**Expected behavior**
It should have just run perfectly fine but instead gave this error:
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more 

**Minecraft server Version**
1.12.2 forge is the version and loader

**Mod/Datapack list**
No mods were loaded.

**Additional context**
Additionally i was using the spanish version of minecolab which seemed easier to operate than the original.

**Comment by N-aksif-N** [comment]
Using java8

**Comment by N-aksif-N** [comment]
:< This may be helped
 https://github.com/thecoder-001/MineColab/issues/100
