### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Healerpro55** [thecoder-001/MineColab#96]
I am having a problem starting the server on paper version 1.8.8 and I think the error is due to the version of java running on the server which is java 17. Maybe there is some way to change the java version to 8 so that it runs correctly. 

[02:19:16 WARN]: java.lang.NoSuchFieldException: modifiers

[02:19:16 WARN]: at java.base/java.lang.Class.getDeclaredField(Class.java:2610)

[02:19:16 WARN]: at org.github.paperspigot.PaperSpigotConfig.stackableBuckets(PaperSpigotConfig.java:192)

[02:19:16 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[02:19:16 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

[02:19:16 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[02:19:16 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:568)

[02:19:16 WARN]: at org.github.paperspigot.PaperSpigotConfig.readConfig(PaperSpigotConfig.java:84)

[02:19:16 WARN]: at org.github.paperspigot.PaperSpigotConfig.init(PaperSpigotConfig.java:62)

[02:19:16 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:181)

[02:19:16 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)

[02:19:16 WARN]: at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by esjuda** [comment]
oh you can do this: 
!sudo apt-get install openjdk-8-jre-headless
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
!update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

This will set java 8 to default
