### ISSUE TITLE
Forge? Java?

### ISSUE THREAD

**Issue by X3bex** [thecoder-001/MineColab#99]
Hello, I have an error in minecolab. When I run the server I get this: apt cache successfully updated
Failed to install OpenJdk16.
Openjdk17 doesn't seem to be installed or isn't working, falling back to java 11 . You might experience reduced performance. Minecraft 1.17 and above might fail to launch.
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/Minecraft-server
colabconfig.json forge-1.12.2-14.23.5.2860.jar libraries server.jar
eula.txt installer.log minecraft_server.1.12.2.jar
Procedure to use ngrok
Get your authtoken from https://dashboard.ngrok.com/auth
Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
Your server address is 0.tcp.sa.ngrok.io:17372
Starting server...
JVM info: Ubuntu - 11.0.21 - 11.0.21+9-post-Ubuntu-0ubuntu122.04
java.net.preferIPv4Stack=true
Found java version 11.0.21
Exception in thread "main"
java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
at java.desktop/java.awt.Window.<init>(Window.java:548)
at java.desktop/java.awt.Frame.<init>(Frame.java:423)
at java.desktop/java.awt.Frame.<init>(Frame.java:388)
at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1689)
at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:868)
at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:670)
at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:641)
at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:177)
at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:147)

**Comment by N-aksif-N** [comment]
Hi @X3bex , this is an advertisement about another project: [Minecolab_Improved](https://github.com/N-aksif-N/MineColab_Improved).

It may be helped you about your issues. Have a nice day!
